site_name: SeqKit - Ultrafast FASTA/Q kit
nav:
- Home: index.md
- Download: download.md
- Usage: usage.md
- FAQ: faq.md
- Tutorial: tutorial.md
- Benchmark: benchmark.md
- Notes: note.md
- More tools: https://github.com/shenwei356
# theme: cinder

theme:
    name: material
    palette:
        primary: teal
        accent: blue grey
    icon:
        logo: material/school
    favicon: files/favicon.ico
    feature:
        navigation.tabs: false
extra:
  manifest: manifest.webmanifest

repo_url: https://github.com/shenwei356/seqkit
site_description: SeqKit - a cross-platform and ultrafast toolkit for FASTA/Q file manipulation
site_author: Wei Shen
google_analytics: ['UA-28948626-9', 'bioinf.shenwei.me/seqkit']
